source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BLParseFetch_Example', :exclusive => true do
  pod 'BLParseFetch', :path => '../'
end

target 'BLParseFetch_Tests', :exclusive => true do
  pod 'BLParseFetch', :path => '../'

  
end
