source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BLParseFetch_Example' do
  pod 'BLParseFetch', :path => '../'
  pod 'BLListDataSource', :git => 'https://github.com/batkov/BLListDataSource'
end
